version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    depends_on:
      - mongo
  mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
